name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.6.2
        arguments: assembleRelease
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "*.apk"
        token: ${{ github.token }}
        generateReleaseNotes: true
